### ISSUE TITLE
create_all_maf_dataframe.py

### ISSUE THREAD

**Issue by ndbrown6** [msk-access/genotype_variants#11]
* genotype_variants version: current
* Python version: 3.7.4 installed via Miniconda
* Operating System: CentOS-7 running on Juno

### Description
Running genotype_variants small_variants all using the command line below. The underlying file create_all_maf_dataframe.py contains errors which prevent python from combining the maf files produced  from the previous steps

### What I Did
1/ Line #111
`df_ds` refers to the combined duplex simplex data frame whilst `df_s` which receives the value of the operation is a subtraction of `df_ds` from another field in `df_s`. `df_ds` does not contain a column with name `t_total_count_forward_standard` since only `df_s` was renamed at Line #73-81

2/ Line #133 and #147, `df_d` is undefined

**Comment by rhshah** [comment]
@ndbrown6  thanks this has been merged into develop #12
